/**
 * @file waternotif.h
 * @author Derek Huang <djh458@stern.nyu.edu>
 * @brief Header file defining the pomwr notification window.
 * @copyright MIT License
 * 
 * Modified from a header file generated by Qt Designer.
 */

#ifndef PWR_WATERNOTIF_H_
#define PWR_WATERNOTIF_H_

#include <memory>

#include <QtCore/QObject>
#include <QtCore/QSize>
#include <QtGui/QFont>
#include <QtGui/QPalette>
#include <QtWidgets/QDialog>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>

namespace pwr {

class WaterNotif: public QDialog
{
  // Q_OBJECT

public:
  WaterNotif();
  WaterNotif(const QPalette &);

// public slots:
//   void emit_yes_signal();
//   void emit_no_signal();

// signals:
//   void yes_signal();
//   void no_signal();

private:
  static const QSize window_size_;
  static const QSize button_size_;
  static const QFont button_font_;
  std::unique_ptr<QPushButton> button_yes_;
  std::unique_ptr<QPushButton> button_no_;
  std::unique_ptr<QLabel> label_decl_;
  std::unique_ptr<QLabel> label_prompt_;
};

} // namespace pwr

#endif // PWR_WATERNOTIF_H_
